name: Build Flatpak Packages
on:
  push:
    branches:
      - master
      - main
      - beta
  pull_request:
    branches:
      - master
      - main
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linters:
    name: "Run linters"
    container:
      image: ghcr.io/flathub/flatpak-builder-lint:latest
      options: --privileged

    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run manifest linters
        run: flatpak-builder-lint --exceptions --user-exceptions .github/linter-exceptions.json manifest org.mozilla.vpn.yml

      - name: Run Appstream linters
        run: flatpak-builder-lint appstream org.mozilla.vpn.metainfo.xml

  build:
    name: "Build Flatpak"
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.9
      options: --privileged
    strategy:
      fail-fast: false
      matrix:
        variant:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.variant.runner }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: mozillavpn.flatpak
          manifest-path: org.mozilla.vpn.yml
          arch: ${{ matrix.variant.arch }}
          cache-key: flatpak-builder-${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.sha }}

      - name: Compress repository
        run: tar -cJf mozillavpn-repo-${{ matrix.variant.arch }}.tar.xz repo

      - name: Upload repository
        uses: actions/upload-artifact@v4
        with:
          name: mozillavpn-repo-${{ matrix.variant.arch }}
          compression-level: 0
          path: mozillavpn-repo-${{ matrix.variant.arch }}.tar.xz

      - name: Run builddir linters
        continue-on-error: true
        run: flatpak-builder-lint builddir flatpak_app

  deploy:
    name: "Deploy repository"
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ostree flatpak

      - name: Import signing keys
        id: keys
        shell: bash
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GNUPGHOME: ${{ runner.temp }}/gnupg-data
        run: |
          mkdir -m700 ${GNUPGHOME}
          echo "$GPG_SIGNING_KEY" | gpg --import --batch
          echo "keyid=$(gpg --with-colons --list-keys | grep -m1 '^fpr:' | tr -d [fpr:])" >> $GITHUB_OUTPUT
          echo "GNUPGHOME=${GNUPGHOME}" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Checkout manifest
        uses: actions/checkout@v4
        with:
          path: manifest
          
      - name: Import repositories
        run: |
          mkdir -p outputs/repo
          ostree init --mode=archive-z2 --repo=outputs/repo
          cp -v $(find manifest -maxdepth 1 -type f) outputs/

          for ARCH in x86_64 aarch64; do
            mkdir repo-${ARCH}
            tar xf artifacts/mozillavpn-repo-${ARCH}.tar.xz -C repo-${ARCH} --strip-components=1

            for REF in $(ostree refs --repo=repo-${ARCH}); do
                flatpak build-commit-from outputs/repo ${REF} \
                    --gpg-sign=${{ steps.keys.outputs.keyid }} \
                    --src-repo=repo-${ARCH} --src-ref=${REF}
            done
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: outputs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
