name: Build Flatpak Packages
on:
  push:
    branches:
      - org.mozilla.vpn
      - beta
  pull_request:
    branches:
      - org.mozilla.vpn
      - beta

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.8
      options: --privileged

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: mozillavpn.flatpak
          manifest-path: org.mozilla.vpn.yml
          cache-key: flatpak-builder-${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.sha }}
