name: Check for updates
on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
  workflow_dispatch: {}

jobs:
  update-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [ main ]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          path: manifest
          ref: ${{ matrix.branch }}

      - name: Parse current upstream
        id: current-upstream
        run: echo "ref=$(./manifest/.github/parse-git-ref.py --module mozillavpn manifest/org.mozilla.vpn.yml)" >> $GITHUB_OUTPUT

      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          # email sets "github-actions[bot]" as commit author, see https://github.community/t/github-actions-bot-email-address/17204/6
          GIT_AUTHOR_EMAIL: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          GIT_COMMITTER_EMAIL: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --commit-only --never-fork manifest/org.mozilla.vpn.yml

      - name: Check for new upstream
        id: latest-upstream
        run: |
          REF=$(./manifest/.github/parse-git-ref.py --module mozillavpn manifest/org.mozilla.vpn.yml)
          if [ "${REF}" != "${{ steps.current-upstream.outputs.ref }}" ]; then
            echo "updated=true" >> $GITHUB_OUTPUT
          fi
          echo "ref=${REF}" >> $GITHUB_OUTPUT

      - uses: actions/setup-python@v5
        if: steps.latest-upstream.outputs.updated == 'true'
        with:
          python-version: 3.11
          cache: pip
      - run: pip install -r manifest/.github/requirements.txt
        if: steps.latest-upstream.outputs.updated == 'true'

      - name: Checkout upstream
        if: steps.latest-upstream.outputs.updated == 'true'
        uses: actions/checkout@v4
        with:
          path: upstream
          repository: mozilla-vpn/mozilla-vpn-client
          ref: ${{ steps.latest-upstream.outputs.ref }}
          sparse-checkout: |
            Cargo.lock
            requirements.in

      - name: Checkout tools
        if: steps.latest-upstream.outputs.updated == 'true'
        uses: actions/checkout@v4
        with:
          path: tools
          repository: flatpak/flatpak-builder-tools
          ref: master

      - name: Update dependencies
        if: steps.latest-upstream.outputs.updated == 'true'
        run: |
          python tools/cargo/flatpak-cargo-generator.py -o manifest/flatpak-vpn-crates.json upstream/Cargo.lock
          python tools/pip/flatpak-pip-generator.py -o manifest/flatpak-glean-parser.yaml --yaml --build-only $(cat upstream/requirements.in | grep glean-parser)
          git -C manifest status
